name: Bun Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: bun testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.34  # or "latest", "canary", <sha>
    - name: bun install and test
      run: |
        bun install
        bun run lint
        bun run test
      env:
        APP_PORT: 3000
